name: Build filtered RSS
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python filter_feed.py
          echo "=== Listing public/ ==="
          ls -lah public || true
          echo "=== Check feed.xml exists ==="
          test -f public/feed.xml || (echo "feed.xml MISSING" && exit 1)
          echo "=== Head of feed.xml ==="
          head -n 20 public/feed.xml || true
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public   # <- on publie UNIQUEMENT public/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
